name: Code Style Checks
on:
  pull_request:
    branches: [ master, Development, backports-1.4 ]

# Restrict the permissions of the ephemeral GitHub token used by this workflow
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v5
      with:
        # Note: Runners may have different, newer .NET SDKs preinstalled.
        # Use global.json to control the maximum acceptable version.
        dotnet-version: '9.x'
    - name: Check C# code style
      run: |
        dotnet format --verify-no-changes Source/CombatExtendedLoader.sln
        dotnet format --verify-no-changes Source/CombatExtended.sln
